/obj/perk/Abilities/GeneralWeaponAbilities
	cat="Genability"
	icon='Icons/Perk/GeneralWeapon.png'
	costtype="Stamina"
	atype="weapon"
	range=" Melee"
	typing="physical"
	element="Physical"
	Melee
		Braver
			rank="D"
			name="Braver"
			desc="The user leaps in a particular direction, gathering momentum in their weapon before striking at a target. Can move an extra 1 tile of movement towards a target of this technique while performing the attack.  (Damage: Weapon damage + 1d10 | Melee attack roll, +3 to hit. -10 stamina.)"
			mcost=10
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 10
			adddam=0
			addhit=3
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
		QuickHit
			rank="D"
			name="Quick Hit"
			mcost=10
			desc="As a bonus action make a quick weapon attack dealing half the damage of a normal attack. (- 10 stamina.)"
		Riposte
			rank="C"
			name="Riposte"
			mcost=10
			basecheck=10
			attack_roll_damage_dice = FALSE
			attack_roll_damage_lower = 0
			attack_roll_damage_upper = 0
			adddam=10
			addhit=0
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user of this ability must first dodge a melee ability. They then carry their momentum over for an augmented blow upon their target. Reaction. This attack is made with advantage. (Damage: Weapon Damage + 10 | Weapon Attack Roll at Advantage | Must first dodge a Melee ability or attack roll via AC. -30 Stamina.)"
		Renzokuken
			rank="C"
			name="Renzokuken"
			mcost=45
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 2
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user of this ability launches forward, moving up to 2 tiles as part of this action. They then release a combination of 3 'Renzokuken' attacks, which deal Weapon Damage+2d2 additional damage on hit. Must be used with a Melee weapon. This ability can not deal more than 80 cumulative damage, regardless of damage rolled across all attacks. Costs 45 Stamina."
		JechtCombo
			rank="C"
			name="Jecht Combination"
			mcost=45
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 2
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="Spell"
			desc="The user of this ability performs an acrobatic, multi-hit attack after infusing their blade with raging 'flames' of passion. This attack deals normal physical damage, as a 3 hit combo. Each attack deals 1d2 additional damage on hit. If at least one hit lands, the 'flames of passion' remain active on the weapon for 3 rounds, granting the the user +5 PDB for 3 rounds. Must be used with a Melee weapon. This ability cannot exceed 45 cumulative damage, regardless of damage rolled. Costs 45 Stamina."
		Halone
			rank="C"
			name="Halone"
			mcost=30
			basecheck=10
			attack_roll_damage_dice = FALSE
			attack_roll_damage_exact = 0
			adddam=5
			addhit=0
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user of this ability swings their weapon after imbuing it with a burst of Mana. The first strike carries through, and if the target dodges, a second strike made of mana and in the shape of the weapon with the same speed follows after (Damage: Weapon Damage + 5 | Bonus action after a standard attack misses. -30 Stamina)"
		StellarCircle
			element="Force"
			rank="C"
			name="Stellar Circle"
			mcost=30
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range=" 5x5 AoE around user."
			costtype="Stamina"
			atype="weaponsave"
			damsource="str"
			typing="physical"
			ptype="spell"
			savetype="Fortitude"
			desc="The user spins their weapon above their head forming a cyclone of magic runes around them. The runes begin to sparkle with star-light, and gravitational draw is induced from them, in a radius around the user. Those with a weak body are drawn towards the target by gravitational waves. (Damage: Weapon damage + 1d12 force | 5x5 AoE, prompts a fortitude saving throw (DC 10+STR+Rank bonus), on a failure creatures take full damage and are drawn 1 tile towards the caster. If a creature is drawn onto the same tile as the caster, it takes an additional 2d10 damage. On a success, take no damage.- 30 stamina.)"
		Launch
			rank="C"
			name="Launch"
			mcost=30
			basecheck=10
			attack_roll_damage_dice = FALSE
			attack_roll_damage_exact = 0
			adddam=4
			addhit=0
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user approaches the target, and using their weapon prepares for a uppercut attack. Instead of actually attacking the user surprises their target by using their weapon to kick up a powerful gale that sends the target upwards leaving them open. This can be used on targets much larger than the user even without a lot of strength. (Damage: Weapon Damage + 4 | Weapon Attack Roll, sends target skyward by 1 tile per STR Modifier point, -30 stamina.)"
		CrossSlash
			rank="C"
			name="Cross Slash"
			mcost=30
			basecheck=10
			attack_roll_damage_dice = FALSE
			attack_roll_damage_exact = 0
			adddam=0
			addhit=0
			range="Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user launches an initial attack with their weapon, and if it hits will lock the target in place as a line is drawn in the air. The user follows up with two more attacks that complete the symbol before releasing the target. The second two attacks are only made if the initial attack hits. This ability can not deal more than 45 damage cumulatively, regardless of damage rolled across all attacks.| Three Melee Attack rolls, prompts a Fortitude saving throw with a DC of 15 - applies stun for one round on failure. -30 stamina.)"
		RoughDivide
			rank="B"
			name="Rough Divide"
			mcost=50
			basecheck=13
			attack_roll_damage_dice = FALSE
			attack_roll_damage_lower = 30
			attack_roll_damage_upper = 70
			atype="weaponsave"
			range=" 3 tile line."
			savetype="Reflex"
			ptype="spell"
			desc="Coating one's weapon in energy, they then dash forward and swing it upward, to blast a target away. This attacks a 3 tile line in front of the caster, and deals full damage on a failed save ; or half on a successful save."
			costtype="Stamina"
		AssaultTrigger
			rank="B"
			name="Assault Trigger"
			mcost=45
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 5
			attack_roll_dice_sides = 2
			atype="weapon"
			range="Melee"
			costtype="Stamina"
			desc="Dash forward, coating one's weapon in volatile magical energy. With each swing, this energy explodes - sending the weapon forward with increase momentum. Each attack deals 5d2 additional damage. In addition, with each attack that misses - grant successive attacks +2 to hit. Make 4 attack rolls. (Capts at 120 cumulative damage.) Costs 45 Stamina."
		FatedCircle
			element="Fire"
			rank="B"
			name="Fated Circle"
			mcost=40
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 6
			adddam=0
			addhit=0
			range=" 3x3 AoE around user."
			costtype="Stamina"
			atype="weaponsave"
			damsource="str"
			typing="physical"
			ptype="spell"
			savetype="Reflex"
			desc="The user makes a sweeping attack with their weapon around them. Explosive energy stored up in the weapon then radiates outward in a sharp, blade-like full circle. The edge of the circle then explodes in a fiery burst, threatening to burn anyone caught in its radius. (Damage: Weapon damage + 2d6+STR fire damage | 3x3 AoE, prompts a relex saving throw (DC 10+STR+Rank bonus), dealing full damage and inflicting burn on a failure, or half damage on a success. -40 stamina.)"
		CrushingBlow
			element="Holy"
			rank="B"
			name="Crushing Blow"
			mcost=50
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 5
			attack_roll_dice_sides = 12
			adddam=5
			addhit=5
			atype="weapon"
			range=" 5 tiles."
			desc="The user of this technique infuses their feet with magic, and launches 3 tiles into the air. They gain the effects of Airborne, without the effects of Knock-up. They then swing their weapon to the side, releasing a disk of light that deals Holy damage, and inflicts 'Heavy' on hit. Attack: Weapon Damage + 5d12. Costs 50 Stamina."
		RoundEdge
			element="Dark"
			rank="B"
			name="Round Edge"
			mcost=50
			attack_roll_damage_dice = FALSE
			attack_roll_damage_lower = 4
			attack_roll_damage_upper = 55
			adddam=3
			addhit=4
			atype="weapon"
			range=" 5x5 AoE"
			costtype="Stamina"
			desc="A massive AoE attack, made by swinging one's weapon in a circular motion, releasing flames of dark energy.. The user makes a melee attack at +4 to hit, hitting all targets around  them in a  5x5 centered on the user. On hit they deal Weapon Damage + 4-55 + 3 Dark Damage. Costs 50 Stamina."
		BladeBeam
			element="Force"
			rank="B"
			name="Blade Beam"
			mcost=40
			basecheck=13
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 12
			adddam=10
			addhit=0
			range=" 6 tile line, 3 tile cone at the end of line."
			costtype="Stamina"
			atype="weaponsave"
			damsource="str"
			typing="physical"
			ptype="spell"
			savetype="Reflex"
			desc="The user draws their sword behind their head before slamming it downward releasing a rather large vertical beam of Mana that carries the same cutting power as the weapon. (Damage: Weapon damage + 2d12 bonus | Reflex Saving throw (DC:10+STR+RB), vs everything in a 3 tile line from the user, then splits into a triad of blade beams, prompting the same to anything in a 3 tile cone at the end of the line. -40 Stamina.)"
		Shout
			name="Shout"
			rank="B"
			mcost=40
			desc="The user turns to their comrades projecting their voice in a powerful boom that instills encouragement in them. Targets all friendly creatures in a 6 tile cone in front of the user. Targets gain haste and a +2 bonus to strength that lasts until the haste effect wears off. Can only be used once per encounter. (-40 Stamina.)"
		BanishingBlade
			name="Banishing Blade"
			rank="B"
			atype="weapon"
			mcost=40
			desc="Runes solidify around the user of this ability's weapon, granting it potent sealing power. They then swing the weapon as a standard attack. On hit, the target is inflicted with Silence. Costs 40 Stamina."
		SlicenDice
			name="Slice n Dice"
			rank="B"
			mcost=60
			atype="weapon"
			desc="A ferocious, and powerful combination attack. This ability allows you to perform 5 Standard attacks, however - only ONE of these five attacks may hit, and deal damage. If any of the five attack rolls would hit, the attack hits - and the user of this ability may choose the highest damage number rolled of the five, to apply.. Costs 60 Stamina."
		GodAmongMen
			element="Force"
			rank="B"
			name="God Among Men"
			mcost=50
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 12
			adddam=0
			addhit=3
			range=" 3 tile cone in front of user."
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user infuses their weapon with magic to make a wide mana based slash, attacking everything in a wide area in front of them. (Damage: Weapon Damage + 2d12+WIS Force damage | Weapon Attack Roll, +3 to hit. | 3 tile cone in front of the user | -50 Mana.)"
		BlastingZone
			rank="A"
			name="Blasting Zone"
			attack_roll_damage_dice = FALSE
			attack_roll_damage_lower = 60
			attack_roll_damage_upper = 110
			basecheck=14
			adddam=5
			mcost=60
			atype="weaponsave"
			savetype="reflex"
			range="3 tile wide, 5 tile line."
			typing="physical"
			damsource="str"
			desc="The user infuses their weapon with obscene amounts of energy, and raises it into the sky. They then swing down, bringing the energy down as a blade, and prompting a reflexing saving throw DC 14 + STR + Rank Bonus. On Failure the take takes 60-110 +5 Physical damage; on success, they take half. Cost -60 Stamina."
		GestaltDrive
			rank="A"
			name="Gestalt Drive"
			atype="weapon"
			mcost=15
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 10
			desc="Calling upon the name of the Valkyries, the user of this ability infuses their weapon with magic that transforms it into a pair of linked together duplicates. They then seperate the blades. This weapon takes the place of their own, and uses its attributes but gains 1d10 additional damage on hit. In addition, while this state is active - you may make an extra attack as a bonus action. Cannot be used with Thief Swords. Costs 15 SP per turn to sustain."
		TriumphantGrasp
			element="Fire"
			rank="A"
			name="Triumphant Grasp"
			mcost=90
			basecheck=15
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 8
			attack_roll_dice_sides = 10
			adddam=0
			addhit=0
			range="Melee"
			costtype="Stamina"
			atype="save"
			damsource="str"
			typing="physical"
			ptype="spell"
			savetype="Strength"
			desc="The user reaches out with a free hand grasping at their opponent. Upon grabbing the target, they drag the target across the ground - and then clench their fist. An explosion erupts from their grasp, and the target is then sent flying at high speeds in a direction of the user's choice. (Damage: 8d10+STR fire damage | STR saving throw (DC 15+STR+Rankbonus) - on a failure, creature is thrown 6 tiles in any direction. Upon hitting a wall, target takes 5d10 additional damage. On a success, attack is negated. -90 Stamina.)"
		ChaosDisaster
			name="Chaotic Disaster"
			element="Dark"
			rank="A"
			mcost=75
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 7
			attack_roll_dice_sides = 10
			adddam=5
			addhit=3
			range=" 5 tile line."
			typing="physical"
			ptype="spell"
			costtype="Stamina"
			desc="The user of this attack swings their weapon in an arc, releasing a beam of energy as a 'Chaotic Disaster' attack roll with +3 to hit, which travels in a 5 tile line, dealing 10d7 + 5 Darkness damage on hit. They then shift to the end of the line, and may make 1 Standard attack roll immediately after.  Costs 75 Stamina."
		LordofArms
			name="Lord of Arms"
			rank="A"
			cat="Unique"
			desc="The user sends out an array of weapons around them controlling them telepathically . They can choose one weapon of each type that they have proficiency in. They make a standard weapon attack roll for each weapon brought out this way. (- 90 stamina.)"
		ArmyofOne
			name="Army of One"
			rank="A"
			cat="Unique"
			desc="The user ignites with a glowing blue aura, and begins flashing around from target to target. They move at tremendous speeds attacking everything hostile around them. They can attack any targets within 15ft around them. There is no limit to the number of targets, but each can only be attacked once. These attacks are made at advantage due to the high speeds. (-10 stamina for each attack made.)"
		FinishingTouch
			rank="A"
			name="Finishing Touch"
			mcost=55
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 20
			adddam=10
			addhit=3
			range="3 tile wide, Melee"
			costtype="Stamina"
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user makes a horizontal slice with their weapon causing the air in front of the user to become disturbed before kicking up a powerful gale that pulls anything caught in it high into the air. Anything that is kicked upwards will most likely take heavy damage from the fall. (Damage: Weapon Damage + 2d20+STR+10 | Melee Weapon Attack (+3 to hit) | 3 tile wide attack, launches target 2 tiles per STR Modifier point. - 55 Stamina)"
		BladeHoning
			rank="A"
			name="Blade Honing"
			desc="Hold your blade in-front of yourself, and channel your spirit into it, becoming one with the weapon itself. At the cost of MP and SP alike ; grant yourself the 'Bravery' status effect, and the chosen weapon gains +1 to hit for the duration of Bravery. (-40 MP, -40 SP.)"
		RedCard
			rank="A"
			cat="Unique"
			name="Red Card"
			mcost=60
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 20
			adddam=0
			addhit=3
			range="Melee"
			costtype="Stamina, pay once per 5 card attacks."
			atype="standard"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="he user takes out a pack of normal playing cards. They scatter the cards over an area. The cards then hover around the area. The user is able to control several all red cards that were placed into the deck causing them to fly around and tear the confused enemy to pieces. (Card Damage: 2d10+DEX| Card Attack Roll: 1d20+DEX+3| The cards cover a 5x5 area in front of the user, the user has 5 red cards inside this area which they can target at anyone inside the AoE twice per turn | 3 round duration, Requires Akademia Cards or Gambler job to be used. -60 Stamina)"
		ThunderGod
			element="Thunder"
			rank="A"
			name="Thunder God"
			mcost=60
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 3
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range="3 tile cone in front of user."
			costtype="Stamina"
			atype="weapon"
			damsource="dex"
			typing="physical"
			ptype="spell"
			desc="The user takes a deep breath, igniting a spark inside them that soon travels through their entire body before reaching their weapon charging it with a fierce amount of electricity. The weapon hums with the built up electrical Mana giving off strands of electricity that latch onto anything it can find. The user then makes a slash towards an opponent releasing the built up Mana expanding the height of the sword for a single moment before the Mana leaves and the blade returns to normal. (Damage: Weapon Damage + 3d12+STR  Thunder damage| Weapon Attack Roll, attacks in 3 tile cone in front of user, -60 Stamina)"
		Innocence
			element="Wind"
			rank="A"
			cat="Unique"
			name="Innocence"
			mcost=70
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 3
			attack_roll_dice_sides = 20
			adddam=0
			addhit=4
			range=" 3 tile wide, 6 tile range."
			costtype="Stamina, per 3 attack rolls."
			atype="weapon"
			damsource="dex"
			typing="physical"
			ptype="spell"
			desc="The user charges energy into their weapon before making two wide slices through the air, creating two blade-beam like projectiles that carry the same power put into the initial slash. (Damage: Weapon Damage + 3d20+DEX each | Ranged Attack Roll (1d20+DEX+4) Creates two separate 3 tile wide projectiles, - 70 Stamina)"
		FulLCharge
			rank="A"
			name="Full Charge"
			mcost=75
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 3
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range="Melee"
			costtype="Stamina, per 4 attack rolls."
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user takes a few moments to gather the energy around them building up a frozen inertia. Once a turn has passed the user launches forward propelling their body with tremendous power and speed. The user spins their body during the assault turning their body into a piercing drill, allowing them to attack several times. (Damage: 3d12+STR | 4 Attack Rolls, takes a turn to charge up, - 75 Stamina | +3 Cooldown.)"
		Octaslash
			rank="S"
			cat="Unique"
			name="Octaslash"
			mcost=120
			basecheck=10
			attack_roll_damage_dice = FALSE
			attack_roll_damage_exact = 0
			adddam=10
			addhit=0
			range="Melee"
			costtype="Stamina, per 8 attack rolls."
			atype="weapon"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user teleports behind a target who is within 5 tiles of them, and delivers 8 powerful slashes in a single debilitating combo. (Damage: Weapon Damage + 10 | 8 Weapon Attack Rolls at advantage (+3 to hit), inflicts Bleed if at least one attack hits. -120 Stamina | 2 Turn Cooldown)"
		OmegaDrive
			rank="S"
			cat="Unique"
			name="Omega Drive"
			mcost=120
			basecheck=18
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 12
			adddam=10
			addhit=0
			range="7x7 AoE"
			costtype="Mana, per 4 attacks."
			atype="save"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user jumps into the air crashing down into an area, and releases a torrential wave of explosive, and chaotic destruction energy. (Damage: 2d12+STR | 4 Seperate 7x7 AoE Attacks, each prompting a Fortitude saving throw, DC 20 - dealing half on a successful save. - 120 Mana | 2 Turn Cooldown)"
		UltimateIllusion
			rank="S"
			cat="Unique"
			name="Ultimate Illusion"
			mcost=120
			basecheck=18
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 4
			attack_roll_dice_sides = 20
			adddam=0
			addhit=0
			range="5 tile cone, up to 4 targets."
			costtype="Mana"
			atype="weaponsave"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user leaps into the air before striking the ground with their weapon, thus sending several waves of energy bursting underground, only to rise from beneath the the target's feet. (Damage: 4d20+STR | Reflex Save, DC 20 (half damage on success). Can strike four different targets in a 5 tile cone in front of the user, - 120 Mana)"
	Ranged
		icon='Icons/Perk/RangedWep.png'
		StoneToss
			element="Earth"
			rank="E"
			name="Stone Toss"
			mcost=5
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range=" 1 tile per STR mod."
			costtype="Stamina"
			atype="standard"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="Pick up a stone tossing it with all your strength. Make an attack roll 1d20 + strength and rank bonus. On a successful hit deal 1d12 bludgeoning damage. Gain +10 to range per STR mod. (Damage: 1d12+STR | Ranged attack roll, STR based. +1 tile per STR mod tile range.)"
		JechtShot
			element="Flare"
			rank="D"
			mcost=10
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 1
			attack_roll_dice_sides = 20
			adddam=0
			addhit=2
			range="Melee"
			costtype="Stamina"
			atype="standard"
			damsource="str"
			typing="physical"
			ptype="spell"
			name="Jecht Shot"
			desc="The user digs a foot into the ground kicking their foot up and sending a soccer sized boulder upwards. The user then jumps upwards and lets their body fall upside down. They then kick the boulder towards their opponent launching it at high speeds. (Damage: 1d20+STR | 6 tile Range, Ranged Attack Roll (1d20+STR+2), -10 stamina)"
		Ricochet
			rank="C"
			name="Ricochet"
			desc="A technique which can be applied to a ranged weapon attack. This gives the attack advantage, and in addition - if the attack misses with advantage applied, it may be re-rolled without advantage immediately after. (Ranged weapon attack, -15 Stamina.)"
		Cripple
			rank="C"
			name="Cripple"
			desc="A technique which can be applied to a ranged weapon attack. If the attack hits, and deals over 15 damage - the target creature is inflicted with Weakness. (Ranged weapon attack, -25 Stamina.)"
		Flameshot
			rank="C"
			name="Flame Shot"
			desc="A technique which can be applied to a ranged weapon attack by lighting it on fire. If the attack hits, the target creature is inflicted with Burn. (Ranged weapon attack, -25 Stamina.)"
		MeteorShot
			rank="C"
			name="Meteor Shot"
			desc="A technique which can be applied to a ranged weapon attack. The weapon is imbued with a powerful shroud of energy at its offending tip, which grants it immense impact force. On hit, the target creature is knocked back 20 feet, and must make a Fortitude saving throw (DC 15) ; or be knocked prone on a failure. (Ranged weapon attack, -20 Stamina.)"
		BloodyShot
			rank="B"
			name="Bloody Shot"
			mcost=45
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 2
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range=" 8 tile range."
			costtype="Stamina"
			atype="weaponsave"
			basecheck=13
			damsource="dex"
			typing="physical"
			ptype="spell"
			savetype="Fortitude"
			desc="A technique which can be applied to a ranged weapon attack. The weapon is imbued with an extra sharp shroud of energy around its offending tip, which grants it additional damage. If the attack roll hits, the target must make a saving throw. (Damage: 2d12+DEX | Prompts a Fortitude saving throw (DC 13+DEX+Rankbonus), dealing full damage and inflict bleed on a failure, and half damage and no bleed on a success. -45 Stamina.)"
		JechtBeam
			element="Flare"
			rank="A"
			cat="Unique"
			name="Jecht Beam"
			mcost=90
			basecheck=18
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 5
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range=" 6 tile wide, 6 tile range."
			costtype="Mana"
			atype="save"
			damsource="str"
			typing="physical"
			savetype="Fortitude"
			ptype="spell"
			desc="The user charges a large orb of magic in their hand. They then release it into a crackling beam that is capable of piercing most defenses. (Damage: 5d12+STR | 6 Tile Wide AoE projectile, 6 tile range, prompts a Fortitude saving throw - taking half damage on a success. Beam ignores 25 points of damage reduction, -90 Mana | 2 Turn Cooldown)"
		UltimateJechtShot
			element="Earth"
			rank="A"
			cat="Unique"
			name="Ultimate Jecht Shot"
			mcost=90
			basecheck=10
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 5
			attack_roll_dice_sides = 12
			adddam=10
			addhit=6
			range=" 6 tile range, 3x3 projectile."
			costtype="Stamina"
			atype="standard"
			damsource="str"
			typing="physical"
			ptype="spell"
			desc="The user digs their hands into the ground pulling up a gigantic boulder. They then throw it upwards letting it soar in the air. The user jumps after it landing on a spot, and then kicking it with their feet launching it towards a target. (Damage: 5d12+STR | Ranged Attack Roll (1d20+STR+6) | 6 tile range, Fires a 2x3 projectile, -90 Stamina | 2 Turn Cooldown)"
		StardustShot
			element="Laser"
			rank="S"
			cat="Unique"
			name="Stardust Shot"
			mcost=120
			basecheck=15
			attack_roll_damage_dice = TRUE
			attack_roll_dice_count = 10
			attack_roll_dice_sides = 12
			adddam=0
			addhit=0
			range=" 7x7 AoE within 10 tiles of user."
			costtype="Stamina"
			atype="weapon"
			damsource="dex"
			typing="physical"
			ptype="spell"
			desc="The user of this technique prepares their ranged weapon, before pumping massive amounts of energy into their prepared shot. They then fire it into the air at an arc, targeting a particular radius within range. The projectile then splits into thousands of glimmering copies, peppering the chosen location with countless piercing rounds. (Damage: 10d12+DEX | Targets a 7x7 AoE, centered on a tile within 10 tiles of the caster. Prompts a Reflex saving throw (15+DEX+Rankbonus), dealing full damage and inflicting Bleed and Slow on a failure, and dealing half damage and inflicting nothing on a success. -120 Stamina.)"
