
// todo: this is shit

#define WEAPON_TIER_BRONZE 1
#define WEAPON_TIER_IRON 2
#define WEAPON_TIER_STEEL 3
#define WEAPON_TIER_MYTHRIL 4
#define WEAPON_TIER_ADAMANTINE 5
#define WEAPON_TIER_ORICHALCUM 6
